jdbc:
  mysql:
    url: jdbc:mysql://localhost:3306/cayenne?connectTimeout=0&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    username: root
    password:

cayenne:
  datasource: mysql
  createSchema: true
