jdbc:
  mysql:
    jdbcUrl: jdbc:mysql://localhost:3306/cayenne?connectTimeout=0&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    maximumPoolSize: 1
    minimumIdle: 1
    username: root
    password:

cayenne:
  datasource: mysql
  createSchema: true
