jdbc:
  mysql:
    jdbcUrl: jdbc:mysql://localhost:3306/cayenne?connectTimeout=0&autoReconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 1
    minimumIdle: 1
    username: root
    password: cayenne
  derby:
    jdbcUrl: jdbc:derby:target/demodb;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    maximumPoolSize: 1
    minimumIdle: 1

cayenne:
  datasource: mysql
  createSchema: false

log:
  level: warn
  appenders:
    - target: stderr
      logFormat: '%highlight(%-5p) %blue([%d{ISO8601,UTC}] %thread %c{20}): %m%n%rEx'
  loggers:
    io.bootique.cayenne.demo:
      level: info
    org.apache.cayenne.log:
      level: info
